version: '3'

services:
    php:
        container_name: events_php
        build: php
        ports:
            - 9092:9092
        expose:
            - 9000
        restart: always
        volumes:
            - ./php/conf/www.conf:/usr/local/etc/php-fpm.d/www.conf
            - ../:/var/www/html
        extra_hosts:
            - "events:172.17.0.1"

networks:
    default:
        driver: bridge
        ipam:
            config:
                - subnet: 172.32.0.0/20